name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: my-portfolio # Checkout into a subfolder
      - name: Build and Deploy
        working-directory: my-portfolio # Change the working directory
        run: |
          mkdir public
          cp -r index.html styles.css images Resume .htaccess public/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: my-portfolio/public
      - uses: actions/deploy-pages@v1
        with:
          artifact_name: website

    