name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: |
          mkdir public
          cp -r index.html styles.css images Resume public/
      - name: Upload Artifact
        id: upload_step # Add an ID to the upload step
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: public
      - name: Deploy to GitHub Pages
        needs: upload_step # Make the deploy step depend on the upload step
        uses: actions/deploy-pages@v1
        with:
          artifact_name: website