name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: |
          mkdir public
          cp -r index.html styles.css images Resume public/
      - name: Upload Artifact # Add this step to upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: website # Give your artifact a name (can be anything)
          path: public  # The path to the directory you want to upload
      - uses: actions/deploy-pages@v1
        with:
          artifact_name: website # The name of the artifact you uploaded
          # folder: public  # Remove folder, artifact_name handles this