name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          build_dir: .  # Use the root directory as the build directory
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          environment: github-pages