name: GitHub Pages

on:
  push:
    branches:
      - main

permissions: # Add this section at the top level
  id-token: write # Grant permission to write the ID token

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: |
          cp -r index.html styles.css images Resume public/
      - uses: actions/deploy-pages@v1
        with:
          folder: public  # No need to specify branch, it uses the pushed branch