name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: |
          # The files are already in the public folder thanks to checkout
          echo "Building website..." # (Add any build commands here if needed)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website # Choose any name for your artifact
          path: public # Path to the public folder in the container
      - uses: actions/deploy-pages@v1
        with:
          artifact_name: website # Must match the artifact name above