name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: |
          mkdir public
          cp -r index.html styles.css images Resume public/
      - name: Upload Artifact
        id: upload_step
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: public
  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:  # Two spaces indentation here
          name: website # Two spaces indentation here
          path: public # Two spaces indentation here
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:  # Two spaces indentation here
          artifact_name: website # Two spaces indentation here